server:
  port: 8080
  servlet:
    context-path: /pet_care_identity

spring:

  datasource:
    url: "jdbc:mysql://localhost:3306/bookteria_identity"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "cnGDY/xuGdmN0zD9ktlVWVA8/Vki3ep0ZiDNJC++DHFSIerOdQJNH4epcyEy+YZR"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds